{{- if .Values.exampleGateway.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.exampleGateway.name | default "invidious-gateway" }}
  namespace: {{ .Values.exampleGateway.namespace | default .Release.Namespace }}
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.exampleGateway.gatewayClassName | default "istio" }}
  listeners:
    {{- range .Values.exampleGateway.listeners }}
    - name: {{ .name }}
      {{- if .hostname }}
      hostname: {{ .hostname }}
      {{- end }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode | default "Terminate" }}
        {{- if .tls.certificateRefs }}
        certificateRefs:
          {{- range .tls.certificateRefs }}
          - name: {{ .name }}
            {{- if .kind }}
            kind: {{ .kind }}
            {{- end }}
            {{- if .group }}
            group: {{ .group }}
            {{- end }}
            {{- if .namespace }}
            namespace: {{ .namespace }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .allowedRoutes }}
      allowedRoutes:
        {{- if .allowedRoutes.namespaces }}
        namespaces:
          from: {{ .allowedRoutes.namespaces.from | default "All" }}
          {{- if .allowedRoutes.namespaces.selector }}
          selector:
            {{- toYaml .allowedRoutes.namespaces.selector | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .allowedRoutes.kinds }}
        kinds:
          {{- range .allowedRoutes.kinds }}
          - group: {{ .group | default "gateway.networking.k8s.io" }}
            kind: {{ .kind }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}