{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "invidious.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowedIngressNamespaces }}
        {{- range .Values.networkPolicy.allowedIngressNamespaces }}
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.networkPolicy.allowedIngressPods }}
        {{- range .Values.networkPolicy.allowedIngressPods }}
        - podSelector:
            matchLabels:
              {{- range $key, $value := . }}
              {{ $key }}: {{ $value }}
              {{- end }}
        {{- end }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- if .Values.companion.enabled }}
    # Allow communication between Invidious and Companion
    - from:
        - podSelector:
            matchLabels:
              {{- include "invidious.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: companion
      ports:
        - protocol: TCP
          port: {{ .Values.companion.service.port }}
    {{- end }}
    {{- if .Values.postgresql.enabled }}
    # Allow communication with PostgreSQL
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
