{{- include "invidious.init-defaults" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
{{- if .Values.existingSecret }}
  annotations:
    # This secret combines the base config with values from external secrets
    helm.sh/resource-policy: keep
{{- end }}
stringData:
  {{- if .Values.existingSecret }}
  # When using existingSecret, we create a template-based config that will be processed by an init container
  INVIDIOUS_CONFIG_TEMPLATE: |
    {{- $config := deepCopy .Values.config }}
    {{/* Set placeholders for values that come from external secrets */}}
    {{- $_ := set $config "invidious_companion_key" "__COMPANION_KEY__" }}
    {{- $_ := set $config "hmac_key" "__HMAC_KEY__" }}
    {{- $_ := set $config.db "password" "__DB_PASSWORD__" }}
    {{- $_ := set $config.db "user" "__DB_USERNAME__" }}
    {{- toYaml $config | nindent 4 }}
  {{- else }}
  # Standard configuration when not using external secrets
  INVIDIOUS_CONFIG: |
    {{- toYaml .Values.config | nindent 4 }}
  {{- end }}
