{{- include "invidious.init-defaults" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
stringData:
  INVIDIOUS_CONFIG: |
    {{/* Build config with secret references resolved */}}
    {{- $config := deepCopy .Values.config }}
    
    {{/* Set companion key from secret if available */}}
    {{- if .Values.existingSecret }}
    {{- $_ := set $config "invidious_companion_key" "FROM_SECRET" }}
    {{- end }}
    
    {{/* Set HMAC key from secret if available */}}
    {{- if .Values.existingSecret }}
    {{- $_ := set $config "hmac_key" "FROM_SECRET" }}
    {{- end }}
    
    {{/* Set DB password from secret if available */}}
    {{- if and .Values.postgresql.enabled .Values.postgresql.auth.existingSecret }}
    {{- $_ := set $config.db "password" "FROM_SECRET" }}
    {{- end }}
    
    {{/* Set DB username from secret if available */}}
    {{- if and .Values.postgresql.enabled .Values.postgresql.auth.existingSecret }}
    {{- $_ := set $config.db "user" "FROM_SECRET" }}
    {{- end }}
    
    {{- toYaml $config | nindent 4 }}
