{{- include "invidious.init-defaults" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
stringData:
  INVIDIOUS_CONFIG: |
    {{/* Build config with secret references resolved */}}
    {{- $config := deepCopy .Values.config }}
    
    {{/* Set companion key from secret if available */}}
    {{- if .Values.existingSecret }}
    {{- $_ := set $config "invidious_companion_key" "FROM_SECRET" }}
    {{- else if and .Values.secrets .Values.secrets.companionKey }}
    {{- $_ := set $config "invidious_companion_key" .Values.secrets.companionKey }}
    {{- end }}
    
    {{/* Set HMAC key from secret if available */}}
    {{- if .Values.existingSecret }}
    {{- $_ := set $config "hmac_key" "FROM_SECRET" }}
    {{- else if and .Values.secrets .Values.secrets.hmacKey }}
    {{- $_ := set $config "hmac_key" .Values.secrets.hmacKey }}
    {{- end }}
    
    {{/* Set DB password from secret if available */}}
    {{- if and .Values.postgresql.enabled .Values.postgresql.auth.existingSecret }}
    {{- $_ := set $config.db "password" "FROM_SECRET" }}
    {{- else if and .Values.secrets .Values.secrets.postgresqlPassword }}
    {{- $_ := set $config.db "password" .Values.secrets.postgresqlPassword }}
    {{- end }}
    
    {{- toYaml $config | nindent 4 }}

---
{{/* Create internal secrets if existingSecret is not provided and secrets are defined */}}
{{- if and (not .Values.existingSecret) .Values.secrets (or .Values.secrets.companionKey .Values.secrets.hmacKey .Values.secrets.postgresqlPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "invidious.fullname" . }}-secrets
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.companionKey }}
  invidious-companion-key: {{ .Values.secrets.companionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.hmacKey }}
  hmac-key: {{ .Values.secrets.hmacKey | quote }}
  {{- end }}
  {{- if .Values.secrets.postgresqlPassword }}
  postgresql-password: {{ .Values.secrets.postgresqlPassword | quote }}
  {{- end }}
{{- end }}
